# Site settings
title: Ali Özgür
header-img: img/home-bg.jpg
email:
description: "Coding and other software development stuff"
# Your website URL (e.g. http://barryclark.github.io or http://www.barryclark.co)
# Used for Sitemap.xml and your RSS feed
url: http://aliozgur.github.io

# If you're hosting your site at a Project repository on GitHub pages
# (http://yourusername.github.io/repository-name)
# and NOT your User repository (http://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
baseurl: ""
twitter_username: aliozgur
github_username:  aliozgur
facebook_username:
linkedin_username: aliozgur
disqus: aliozgur
google_analytics:


# Build settings
markdown: redcarpet
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
